/**
 * night-mode
 *
 * Overnight babysitting for long agent runs.
 *
 * Between 21:00 and 09:00 local:
 *  1. holds a `caffeinate -dimsu` process while an agent run is in flight (or
 *     while paused waiting for a reset) so the machine never sleeps mid-run,
 *  2. watches the Claude 5h subscription window (published by the `usage`
 *     extension on the event bus) and pauses the agent at 95% so the session
 *     never spills past the limit,
 *  3. records the pause in the session, then auto-sends a "continue" prompt
 *     once the window has reset.
 *
 * Pausing works by blocking every tool call in the current batch with
 * `terminate: true`, which ends the agent loop at a clean boundary. Nothing is
 * dropped: the transcript keeps everything and the resume prompt picks it up.
 *
 * State is per session, per pi instance. Emits `night-mode:state` on the bus.
 */

import { type ChildProcess, spawn } from "node:child_process";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import {
	FIVE_HOUR_LABEL,
	USAGE_REQUEST_EVENT,
	USAGE_SNAPSHOT_EVENT,
	type UsageSnapshot,
	findWindow,
	isUsageSnapshotEvent,
} from "../usage/protocol.ts";
import {
	DEFAULT_THRESHOLD_PERCENT,
	DEFAULT_WINDOW,
	type NightWindow,
	RESUME_RETRY_MS,
	computeResumeDelayMs,
	formatClock,
	formatDuration,
	formatWindow,
	isWithinWindow,
	shouldHoldCaffeinate,
	shouldPause,
	windowStartingAt,
} from "./night-mode.ts";

const TICK_MS = 30_000;
const STATUS_KEY = "night-mode";
const PAUSE_ENTRY = "night-mode:pause";
const STATE_EVENT = "night-mode:state";

const RESUME_PROMPT =
	"[night-mode] Automated resume: the Claude 5h usage window has reset. " +
	"This message was generated by the night-mode extension, not by the user, " +
	"and is not an approval for anything that was pending. " +
	"Continue the work you were interrupted on.";

export interface NightModeState {
	enabled: boolean;
	inWindow: boolean;
	paused: boolean;
	/** Epoch ms of the scheduled resume attempt, when paused. */
	resumeAt?: number;
	usedPercent?: number;
	threshold: number;
	/** True while an agent run is in flight (between `agent_start` and `agent_settled`). */
	agentBusy: boolean;
	/** True while this session holds a `caffeinate` process. */
	caffeinated: boolean;
}

export default function (pi: ExtensionAPI): void {
	let ctxRef: ExtensionContext | undefined;
	let caffeinate: ChildProcess | undefined;
	let usage: UsageSnapshot | undefined;
	let enabled = true;
	let inWindow = false;
	let paused = false;
	/** True between `agent_start` and `agent_settled`. */
	let agentBusy = false;
	let resumeAt: number | undefined;
	let resumeTimer: ReturnType<typeof setTimeout> | undefined;
	let tickTimer: ReturnType<typeof setInterval> | undefined;
	let unsubscribeUsage: (() => void) | undefined;
	/** Session-only window override, set by `/night start`. */
	let windowOverride: NightWindow | undefined;

	const currentWindow = (): NightWindow => windowOverride ?? DEFAULT_WINDOW;

	const fiveHour = () => findWindow(usage, FIVE_HOUR_LABEL);
	const usedPercent = () => fiveHour()?.usedPercent;

	// ── caffeinate ────────────────────────────────────────────────────────

	function startCaffeinate(): void {
		if (process.platform !== "darwin" || caffeinate) return;
		try {
			// -d display, -i idle sleep, -m disk, -s system sleep on AC, -u user active.
			const child = spawn("caffeinate", ["-dimsu"], { stdio: "ignore" });
			child.on("error", () => {
				if (caffeinate === child) caffeinate = undefined;
			});
			child.on("exit", () => {
				if (caffeinate === child) caffeinate = undefined;
			});
			child.unref?.();
			caffeinate = child;
		} catch {
			caffeinate = undefined;
		}
	}

	function stopCaffeinate(): void {
		if (!caffeinate) return;
		try {
			caffeinate.kill();
		} catch {
			// already gone
		}
		caffeinate = undefined;
	}

	// ── state reporting ───────────────────────────────────────────────────

	function snapshotState(): NightModeState {
		return {
			enabled,
			inWindow,
			paused,
			resumeAt,
			usedPercent: usedPercent(),
			threshold: DEFAULT_THRESHOLD_PERCENT,
			agentBusy,
			caffeinated: caffeinate !== undefined,
		};
	}

	function statusText(): string | undefined {
		if (!enabled || !inWindow) return undefined;
		if (paused) {
			const left = resumeAt ? formatDuration(resumeAt - Date.now()) : "?";
			return `\u{1F319} paused (5h ${Math.round(usedPercent() ?? 100)}%) \u27F3 ${left}`;
		}
		const pct = usedPercent();
		return pct === undefined ? "\u{1F319} night" : `\u{1F319} night (5h ${Math.round(pct)}%)`;
	}

	function report(): void {
		ctxRef?.ui.setStatus(STATUS_KEY, statusText());
		pi.events.emit(STATE_EVENT, snapshotState());
	}

	// ── pause / resume ────────────────────────────────────────────────────

	function clearResumeTimer(): void {
		if (resumeTimer) {
			clearTimeout(resumeTimer);
			resumeTimer = undefined;
		}
	}

	function armResume(delayMs: number): void {
		clearResumeTimer();
		resumeAt = Date.now() + delayMs;
		resumeTimer = setTimeout(() => void resume(), delayMs);
		resumeTimer.unref?.();
	}

	function scheduleResume(): void {
		armResume(computeResumeDelayMs(fiveHour()?.resetsAt, Date.now()));
	}

	function pause(): void {
		if (paused) return;
		paused = true;
		scheduleResume();
		pi.appendEntry(PAUSE_ENTRY, {
			status: "paused",
			at: new Date().toISOString(),
			usedPercent: usedPercent(),
			resetsAt: fiveHour()?.resetsAt,
			resumeAt,
		});
		report();
		if (resumeAt) {
			ctxRef?.ui.notify(
				`night-mode: Claude 5h window at ${Math.round(usedPercent() ?? 100)}%, pausing until ${formatClock(new Date(resumeAt))}`,
				"warning",
			);
		}
	}

	function clearPause(): void {
		if (!paused) return;
		paused = false;
		resumeAt = undefined;
		clearResumeTimer();
		report();
	}

	async function resume(): Promise<void> {
		resumeTimer = undefined;
		if (!paused) return;

		// Ask for a fresh reading before trusting the reset.
		pi.events.emit(USAGE_REQUEST_EVENT, { reason: "night-mode-resume" });
		if (shouldPause(usedPercent())) {
			armResume(RESUME_RETRY_MS);
			report();
			return;
		}

		paused = false;
		resumeAt = undefined;
		clearResumeTimer();
		pi.appendEntry(PAUSE_ENTRY, {
			status: "resumed",
			at: new Date().toISOString(),
			usedPercent: usedPercent(),
		});
		report();
		ctxRef?.ui.notify("night-mode: 5h window reset, sending automated continue", "info");
		pi.sendUserMessage(RESUME_PROMPT, { deliverAs: "followUp" });
	}

	// ── evaluation ────────────────────────────────────────────────────────

	/** Take or release the caffeinate process to match the current state. */
	function syncCaffeinate(): void {
		if (shouldHoldCaffeinate({ enabled, inWindow, agentBusy, paused })) startCaffeinate();
		else stopCaffeinate();
	}

	function evaluate(): void {
		const active = enabled && isWithinWindow(new Date(), currentWindow());
		if (active !== inWindow) {
			inWindow = active;
			if (!active) clearPause();
		}
		if (inWindow && !paused && shouldPause(usedPercent())) pause();
		syncCaffeinate();
		report();
	}

	/** Re-arm a pause recorded before a `/reload` or session resume. */
	function restore(ctx: ExtensionContext): void {
		try {
			const entries = ctx.sessionManager.getEntries() as Array<{ customType?: string; data?: unknown }>;
			for (let i = entries.length - 1; i >= 0; i--) {
				const entry = entries[i];
				if (entry?.customType !== PAUSE_ENTRY) continue;
				const data = entry.data as { status?: string; resumeAt?: number } | undefined;
				if (data?.status === "paused") {
					paused = true;
					armResume(Math.max(0, (data.resumeAt ?? Date.now()) - Date.now()));
				}
				return;
			}
		} catch {
			// no session history available
		}
	}

	// ── wiring ───────────────────────────────────────────────────────────

	unsubscribeUsage = pi.events.on(USAGE_SNAPSHOT_EVENT, (data) => {
		if (!isUsageSnapshotEvent(data)) return;
		usage = data.snapshot;
		evaluate();
	});

	pi.on("session_start", async (_event, ctx) => {
		ctxRef = ctx;
		restore(ctx);
		pi.events.emit(USAGE_REQUEST_EVENT, { reason: "night-mode-start" });
		if (!tickTimer) {
			tickTimer = setInterval(() => evaluate(), TICK_MS);
			tickTimer.unref?.();
		}
		evaluate();
	});

	pi.on("agent_start", () => {
		agentBusy = true;
		evaluate();
	});

	// `agent_settled` (not `agent_end`) is the real "nothing left to do" signal: no
	// retry, compaction or queued continuation will follow.
	pi.on("agent_settled", () => {
		agentBusy = false;
		evaluate();
	});

	pi.on("tool_call", (_event, ctx) => {
		ctxRef = ctx;
		if (!enabled || !inWindow || !paused) return;
		const until = resumeAt ? formatClock(new Date(resumeAt)) : "the next window";
		return {
			block: true,
			terminate: true,
			reason:
				`night-mode: Claude 5h usage window at ${Math.round(usedPercent() ?? 100)}% ` +
				`(limit ${DEFAULT_THRESHOLD_PERCENT}%). Stopping here until ${until}, ` +
				"when an automated continue will be sent. Do not retry.",
		};
	});

	pi.on("session_shutdown", async () => {
		stopCaffeinate();
		clearResumeTimer();
		if (tickTimer) {
			clearInterval(tickTimer);
			tickTimer = undefined;
		}
		unsubscribeUsage?.();
		unsubscribeUsage = undefined;
	});

	pi.registerCommand("night", {
		description:
			"Night mode: caffeinate + Claude 5h budget guard (status | start | on | off | resume)",
		getArgumentCompletions: (prefix) =>
			["status", "start", "on", "off", "resume"]
				.filter((v) => v.startsWith(prefix))
				.map((value) => ({ value, label: value })),
		handler: async (args, ctx) => {
			ctxRef = ctx;
			const action = args.trim().toLowerCase();

			if (action === "start") {
				enabled = true;
				windowOverride = windowStartingAt(new Date());
				evaluate();
				ctx.ui.notify(
					`night-mode: started now, window ${formatWindow(currentWindow())} for this session`,
					"info",
				);
				return;
			}

			if (action === "on" || action === "off") {
				enabled = action === "on";
				if (!enabled) {
					stopCaffeinate();
					clearPause();
					inWindow = false;
					windowOverride = undefined;
				}
				evaluate();
				ctx.ui.notify(`night-mode: ${enabled ? "enabled" : "disabled"}`, "info");
				return;
			}

			if (action === "resume") {
				if (!paused) {
					ctx.ui.notify("night-mode: not paused", "info");
					return;
				}
				clearPause();
				pi.sendUserMessage(RESUME_PROMPT, { deliverAs: "followUp" });
				return;
			}

			const pct = usedPercent();
			const resets = fiveHour()?.resetsAt;
			const lines = [
				`night-mode: ${enabled ? "enabled" : "disabled"}`,
				`window: ${formatWindow(currentWindow())} (${inWindow ? "inside" : "outside"}${windowOverride ? ", session override" : ""})`,
				`caffeinate: ${caffeinate ? "holding" : "off"}`,
				`5h usage: ${pct === undefined ? "unknown" : `${Math.round(pct)}% / ${DEFAULT_THRESHOLD_PERCENT}%`}`,
				`5h reset: ${resets ? formatDuration(new Date(resets).getTime() - Date.now()) : "unknown"}`,
				`paused: ${paused ? `yes, resume in ${resumeAt ? formatDuration(resumeAt - Date.now()) : "?"}` : "no"}`,
			];
			ctx.ui.notify(lines.join("\n"), "info");
		},
	});
}
