/**
 * Composition of the `/night start` prompt and of the report skeleton.
 *
 * Pure string building so the wiring in `index.ts` only does I/O.
 */

import { DEFAULT_REPORT_SECTIONS, formatDateTimeStamp } from "./config.ts";
import { formatDayStamp, type PauseReason } from "./night-mode.ts";

export interface NightPromptInput {
	/** Body of the configured base prompt file. */
	prompt: string;
	/** Body of the extra instructions file. Blank when there is nothing extra. */
	instructions: string;
	/** Absolute path of the report to write. */
	reportPath: string;
	/** Hard cap on pull requests for the night. */
	maxPullRequests: number;
	/** Human window label, e.g. `21:00-09:00`. */
	windowLabel: string;
	/** Run start, used for the header stamp. */
	startedAt: Date;
	/** Identity of tonight's run: every ledger item is tagged with it. */
	runId?: string;
	/** Per-run working copy, when one was created for tonight. */
	workspacePath?: string;
	/** Where the sandbox capability probe writes what tonight actually allows. */
	preflightPath?: string;
}

/** True when a file body carries no actual instruction. */
export function hasInstructions(body: string): boolean {
	return body.replace(/^---[\s\S]*?---/, "").trim().length > 0;
}

/**
 * The coordinator's own contract: it orchestrates, it does not implement.
 *
 * This lives in the extension rather than in the base prompt file so it applies
 * to every night prompt and cannot drift. Without it the agent reads the whole
 * routine, does the first item inline "since it is small", and burns its
 * context budget on file reads instead of on picking the next unit of work.
 */
export const ORCHESTRATOR_CONTRACT = [
	"## Your role: orchestrator",
	"",
	"You coordinate, you do not implement. Your context is the scarce resource tonight: spend it on triage, on",
	"choosing the next unit of work and on the report, never on the contents of the files a task touches.",
	"",
	"- One ledger item is one subagent run. Delegate it with the `run` tool of the `agents` provider.",
	"- Always pass `night: true`. That injects the hard rules into the child, so they cannot be lost.",
	"- Omit `agent` (or pass `task`) unless a specific persona clearly fits. A generic subagent inherits your",
	"  model, tools, skills and project context.",
	"- Pass the how-to as `reads` instead of pasting it into the task: the child loads those files itself.",
	"- Pass an `output` path when the result is long, then append that file to the report without reading it.",
	"- Every task message states: the goal, the repo and the base to branch from, the matching ledger item, the",
	"  definition of done, and that the final message must end with an `Evidence:` line.",
	"- Run one subagent at a time per repository. Two children creating changes in the same working copy fight.",
	"- You own the report file exclusively. Subagents never write to it; you append from what they hand back.",
	"- You may read files to triage and to write the report. Implementing a ledger item yourself, reading a",
	"  source tree to fix something, or running a repo's tests is a delegation you skipped.",
].join("\n");

/** The message `/night start` sends to the agent. */
export function composeNightPrompt(input: NightPromptInput): string {
	const sections: string[] = [
		"[night-mode] Automated night run. This message was generated by the night-mode extension, not typed by the user. " +
			"Nobody is awake: never ask a question, never wait for confirmation.",
		"",
		`Window: ${input.windowLabel}. Started ${formatDateTimeStamp(input.startedAt)}.`,
		`Report file: \`${input.reportPath}\` - create it now and append to it as you go, not once at the end.`,
		`Pull request cap for tonight: ${input.maxPullRequests}. Stop opening PRs once you reach it and log what is left.`,
		...(input.workspacePath
			? [
					`Working copy: \`${input.workspacePath}\` - a private clone of the repo made for tonight. Work there, and ` +
						"tell every subagent to do the same. The user's own checkout is off limits.",
				]
			: []),
		...(input.preflightPath
			? [
					`Sandbox capabilities: \`${input.preflightPath}\` - written a few seconds into the run by a probe of this ` +
						"sandbox (HTTPS egress, DNS, SSH, `gh`, `jj`, loopback TCP). Read it before planning, and point " +
						"subagents at it instead of letting them rediscover the envelope one burnt run at a time.",
				]
			: []),
		"",
		ORCHESTRATOR_CONTRACT,
		"",
		"Ledger: before doing any work, enumerate everything tonight covers as todos tagged `night`" +
			(input.runId ? ` and \`run:${input.runId}\`` : "") +
			", one per unit of work. The ledger, not your judgement, decides when the night is over: settling with " +
			"`night` todos still open triggers an automated continuation.",
		"",
		"Closing an item takes typed evidence, and the todo tool refuses the write without it:",
		"",
		"- `done` plus one of `Evidence: file /abs/path`, `Evidence: commit <id> (repo: /abs/repo)`, " +
			"`Evidence: pr <url>`, `Evidence: url <url>`, `Evidence: none-with-reason <why there is nothing to point at>`,",
		"- or `skipped` plus a `Reason:` line.",
		"",
		"The evidence is then checked: a `file` that does not exist or is empty, or a `commit` that does not resolve, " +
			"flips the item to needs-review and it keeps counting as open. Do not claim an artifact you have not seen on " +
			"disk, and require the same of every subagent.",
		"",
		"---",
		"",
		input.prompt.trim(),
	];

	sections.push("", "---", "", "## Extra instructions for tonight", "");
	if (hasInstructions(input.instructions)) {
		sections.push(
			"These come straight from the user and take priority over the default routine.",
			"",
			input.instructions.trim(),
		);
	} else {
		sections.push("None tonight. Run the default routine above.");
	}

	return `${sections.join("\n")}\n`;
}

/**
 * The report file's initial content, written before the agent starts. Sections
 * come from `nightMode.reportSections`, so the skeleton matches whatever the
 * base prompt asks the agent to fill in.
 */
export function composeReportHeader(
	startedAt: Date,
	windowLabel: string,
	sections: string[] = DEFAULT_REPORT_SECTIONS,
): string {
	return [
		"---",
		"tags:",
		"  - night-report",
		"---",
		`# Night Report - ${formatDateTimeStamp(startedAt)}`,
		"",
		`Window: ${windowLabel}`,
		"",
		...sections.flatMap((section) => [`## ${section}`, ""]),
	].join("\n");
}

/**
 * The follow-up sent when the agent settles with ledger items still open. The
 * framing matters: the agent just decided it was finished, so this has to be an
 * instruction, not a suggestion.
 */
export function composeNudge(input: {
	unresolved: string;
	reportPath: string;
	attempt: number;
	maxAttempts: number;
}): string {
	return [
		"[night-mode] Automated continuation. This message was generated by the night-mode extension, not by the user, " +
			"and is not an approval for anything that was pending.",
		"",
		"The night ledger still has unresolved items, so the run is not over:",
		"",
		input.unresolved,
		"",
		"Pick the next one and finish it. To close an item, set its status to `done` and put a typed `Evidence:` line " +
			"in the todo body (`file /abs/path`, `commit <id> (repo: /abs/repo)`, `pr <url>`, `url <url>`, " +
			"`none-with-reason <why>`). To drop one, set its status to `skipped` and put a `Reason:` line. The write is " +
			"refused without one, and evidence that does not check out keeps the item open.",
		"You are still the orchestrator: delegate the item to a subagent with `night: true` rather than implementing " +
			"it yourself, and append to the report from what it hands back.",
		`Keep appending to \`${input.reportPath}\` as you go.`,
		`(continuation ${input.attempt}/${input.maxAttempts})`,
		"",
	].join("\n");
}

/** The first nudge, when the agent settled without ever building a ledger. */
export function composeLedgerReminder(reportPath: string): string {
	return [
		"[night-mode] Automated continuation, generated by the night-mode extension.",
		"",
		"The night ledger is empty: no todo tagged `night` exists. Enumerate tonight's work as todos before doing " +
			"anything else, one per unit of work, tag each one `night`, then work through them.",
		`Report: \`${reportPath}\`.`,
		"",
	].join("\n");
}

/**
 * Insert lines under an existing `## Heading`, just before the next heading.
 * Falls back to appending at the end when the heading is missing, so a report
 * the agent restructured never loses the content.
 */
export function appendUnderHeading(body: string, heading: string, text: string): string {
	const lines = body.split("\n");
	const start = lines.findIndex((line) => line.trim().toLowerCase() === `## ${heading}`.toLowerCase());
	if (start === -1) return `${body.replace(/\s*$/, "")}\n\n## ${heading}\n\n${text.replace(/\s*$/, "")}\n`;

	let end = lines.length;
	for (let i = start + 1; i < lines.length; i++) {
		if (lines[i].startsWith("## ")) {
			end = i;
			break;
		}
	}
	// Drop the blank padding before the next heading, then re-add exactly one.
	let insert = end;
	while (insert > start + 1 && lines[insert - 1].trim() === "") insert -= 1;
	const payload = text.replace(/\s*$/, "").split("\n");
	lines.splice(insert, 0, ...payload, "");
	return lines.join("\n");
}

/**
 * The block seeded into the instructions file for the next night. Unfinished
 * work becomes tomorrow's top priority instead of evaporating at sunrise.
 */
export function composeCarryOver(startedAt: Date, unresolvedList: string, reportPath: string): string {
	return [
		`## Carried over from the night of ${formatDateTimeStamp(startedAt)}`,
		"",
		"These were still open when the run ended. Start with them.",
		"",
		unresolvedList,
		"",
		`Previous report: \`${reportPath}\``,
		"",
	].join("\n");
}

export interface ResumePromptInput {
	/** Which limit had stopped the run. */
	reason: PauseReason;
	/** Now, so the agent knows which day it woke up on. */
	now: Date;
	/** When the pause started, when it is known. */
	pausedAt?: Date;
}

/**
 * The follow-up sent when a pause is lifted.
 *
 * It carries the current day on purpose: a 5h pause costs hours, but a weekly
 * one can cost days, and an agent that resumes with a stale idea of "now" acts
 * on branches, PRs and CI results that have moved since.
 */
export function composeResumePrompt(input: ResumePromptInput): string {
	const limit = input.reason === "week" ? "weekly usage limit" : "5h usage window";
	const lines = [
		`[night-mode] Automated resume: the Claude ${limit} has room again. This message was generated by the ` +
			"night-mode extension, not by the user, and is not an approval for anything that was pending.",
		"",
		`It is now ${formatDayStamp(input.now)}.` +
			(input.pausedAt ? ` The run was paused at ${formatDayStamp(input.pausedAt)}.` : ""),
	];
	if (input.reason === "week") {
		lines.push(
			"A weekly pause can span days. Re-read the ledger and the report before acting, and re-check anything you " +
				"had in flight (branches, pull requests, CI runs, ticket state) instead of assuming it is where you left it.",
		);
	}
	lines.push("", "Continue the work you were interrupted on.", "");
	return lines.join("\n");
}

/** A `## Timeline` line appended by the extension itself (pause, resume, end). */
export function timelineLine(at: Date, text: string): string {
	const hh = String(at.getHours()).padStart(2, "0");
	const mm = String(at.getMinutes()).padStart(2, "0");
	return `- ${hh}:${mm} ${text}\n`;
}
